@startuml
/'
UCF COP3330 Fall 2021 Assignment 4 Solution
Copyright 2021 Reese Stowell
'/
Class HelloController
{
FileChooser fileChooser
private TableView<Items> table;
private TableColumn<Items, Integer> id;
private TableColumn<Items, String> Description;
private TableColumn<Items, LocalDate> DueDate;
private TableColumn<Items, Boolean> Status;
private Button Add;
private Button Delete;
private Button SaveEdit;
private Button ShowComplete;
private Button ShowIncomplete;
private Button ClearList;
private Button ShowAll;
private Button Save;
private Button Load;
private javafx.scene.control.TextArea TextArea;
private DatePicker DateBox;
private CheckBox CheckBox;
public ObservableList<Items> list
AddPressJunit(ActionEvent)
AddPress(int, String, LocalDate, String)
DeletePressJunit(ActionEvent)
DeletePress(Items)
SaveEditPressJunit(ActionEvent)
SaveEditPress(Items, String, LocalDate, String)
ShowCompletePressJunit(ActionEvent)
ShowCompletePress(ObservableList<Items>)
ShowIncompletePressJunit(ActionEvent)
ClearListPressJunit(ActionEvent)
ClearListPress()
ShowAllPress(ObservableList<Items> listAll)
SavePressJunit(ActionEvent)
SavePress(File)
LoadPressJunit(ActionEvent)
LoadPress(File)
initialize(URL location, ResourceBundle resources)
}


Class Item
{
int id
String Description
LocalDate Date
String Status
}

Class HelloApplication
{
start(Stage stage)
main()
}

HelloController -- Item: > Creates, Uses, and Holds
HelloApplication -- HelloController: > Uses


@enduml